from . import help
from . import menuHandler
from . import kurs_kantaktHandler
from . import kantaktHandler
from . import vakansiyaHandler
from . import uzb_menuHandler
from . import contactHandler
from . import course_contacthandler
from . import vacancyHandler
from . import start
from . import echo